version: 2
project_name: hermod

before:
  hooks:
    - go mod tidy

builds:
  - id: hermod
    main: ./cmd/hermod
    binary: hermod
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w

  - id: hermod-edge
    main: ./cmd/hermod-edge
    binary: hermod-edge
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w

  - id: hermodctl
    main: ./cmd/hermodctl
    binary: hermodctl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - config.yaml

nfpms:
  - file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    homepage: https://github.com/user/hermod
    maintainer: Hermod Team <support@hermod.io>
    description: Enterprise-Grade Data Integration & Streaming Platform
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
