// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: pkg/source/grpc/proto/source.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The path configured on the gRPC source, sent exactly as configured — for
	// example "/grpc/orders". It is a routing label, not a URL. Empty means
	// "/grpc/default". The source only receives while its workflow is running.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Record ID. Hermod generates one when this is empty.
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Optional change type: "create", "update", "delete" or "snapshot". When it
	// is set the record is treated as a change event, and its fields are read as
	// "after.<field>" in the workflow rather than as "<field>".
	Operation string `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`
	// Optional table and schema the record belongs to.
	Table  string `protobuf:"bytes,4,opt,name=table,proto3" json:"table,omitempty"`
	Schema string `protobuf:"bytes,5,opt,name=schema,proto3" json:"schema,omitempty"`
	// Optional previous row image for a change event, as a JSON object.
	Before []byte `protobuf:"bytes,6,opt,name=before,proto3" json:"before,omitempty"`
	// The record, as a JSON object. Used when payload is empty.
	After []byte `protobuf:"bytes,7,opt,name=after,proto3" json:"after,omitempty"`
	// The record, as a JSON object. Takes precedence over after.
	//
	// These are bytes: a generated client passes the JSON text as-is, and a
	// JSON-speaking tool such as grpcurl or "buf curl" needs it base64-encoded.
	Payload []byte `protobuf:"bytes,8,opt,name=payload,proto3" json:"payload,omitempty"`
	// Free-form string metadata carried alongside the record.
	Metadata      map[string]string `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_pkg_source_grpc_proto_source_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_source_grpc_proto_source_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_pkg_source_grpc_proto_source_proto_rawDescGZIP(), []int{0}
}

func (x *PublishRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PublishRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PublishRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *PublishRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *PublishRequest) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *PublishRequest) GetBefore() []byte {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *PublishRequest) GetAfter() []byte {
	if x != nil {
		return x.After
	}
	return nil
}

func (x *PublishRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PublishRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type PublishResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The record's ID: the one sent, or the one Hermod generated.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// "dispatched" when the record was queued for the workflow. A source that
	// responds synchronously reports what the workflow did instead: "delivered",
	// "completed" (it ran and had nothing to write), "dead_lettered" or "failed",
	// or "pending" when the wait ran out before the workflow finished.
	// PublishStream also answers "rejected" for a record it could not queue.
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// Why the record failed. Set for "dead_lettered" and "failed".
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// The record as the workflow left it, as a JSON object. Set by a source that
	// responds synchronously.
	Record        []byte `protobuf:"bytes,4,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_pkg_source_grpc_proto_source_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_source_grpc_proto_source_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_pkg_source_grpc_proto_source_proto_rawDescGZIP(), []int{1}
}

func (x *PublishResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PublishResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PublishResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PublishResponse) GetRecord() []byte {
	if x != nil {
		return x.Record
	}
	return nil
}

var File_pkg_source_grpc_proto_source_proto protoreflect.FileDescriptor

const file_pkg_source_grpc_proto_source_proto_rawDesc = "" +
	"\n" +
	"\"pkg/source/grpc/proto/source.proto\x12\x15hermod.source.grpc.v1\"\xd6\x02\n" +
	"\x0ePublishRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1c\n" +
	"\toperation\x18\x03 \x01(\tR\toperation\x12\x14\n" +
	"\x05table\x18\x04 \x01(\tR\x05table\x12\x16\n" +
	"\x06schema\x18\x05 \x01(\tR\x06schema\x12\x16\n" +
	"\x06before\x18\x06 \x01(\fR\x06before\x12\x14\n" +
	"\x05after\x18\a \x01(\fR\x05after\x12\x18\n" +
	"\apayload\x18\b \x01(\fR\apayload\x12O\n" +
	"\bmetadata\x18\t \x03(\v23.hermod.source.grpc.v1.PublishRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"g\n" +
	"\x0fPublishResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x16\n" +
	"\x06record\x18\x04 \x01(\fR\x06record2\xcd\x01\n" +
	"\rSourceService\x12X\n" +
	"\aPublish\x12%.hermod.source.grpc.v1.PublishRequest\x1a&.hermod.source.grpc.v1.PublishResponse\x12b\n" +
	"\rPublishStream\x12%.hermod.source.grpc.v1.PublishRequest\x1a&.hermod.source.grpc.v1.PublishResponse(\x010\x01B7Z5github.com/gsoultan/hermod/pkg/comm/source/grpc/protob\x06proto3"

var (
	file_pkg_source_grpc_proto_source_proto_rawDescOnce sync.Once
	file_pkg_source_grpc_proto_source_proto_rawDescData []byte
)

func file_pkg_source_grpc_proto_source_proto_rawDescGZIP() []byte {
	file_pkg_source_grpc_proto_source_proto_rawDescOnce.Do(func() {
		file_pkg_source_grpc_proto_source_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_source_grpc_proto_source_proto_rawDesc), len(file_pkg_source_grpc_proto_source_proto_rawDesc)))
	})
	return file_pkg_source_grpc_proto_source_proto_rawDescData
}

var file_pkg_source_grpc_proto_source_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_source_grpc_proto_source_proto_goTypes = []any{
	(*PublishRequest)(nil),  // 0: hermod.source.grpc.v1.PublishRequest
	(*PublishResponse)(nil), // 1: hermod.source.grpc.v1.PublishResponse
	nil,                     // 2: hermod.source.grpc.v1.PublishRequest.MetadataEntry
}
var file_pkg_source_grpc_proto_source_proto_depIdxs = []int32{
	2, // 0: hermod.source.grpc.v1.PublishRequest.metadata:type_name -> hermod.source.grpc.v1.PublishRequest.MetadataEntry
	0, // 1: hermod.source.grpc.v1.SourceService.Publish:input_type -> hermod.source.grpc.v1.PublishRequest
	0, // 2: hermod.source.grpc.v1.SourceService.PublishStream:input_type -> hermod.source.grpc.v1.PublishRequest
	1, // 3: hermod.source.grpc.v1.SourceService.Publish:output_type -> hermod.source.grpc.v1.PublishResponse
	1, // 4: hermod.source.grpc.v1.SourceService.PublishStream:output_type -> hermod.source.grpc.v1.PublishResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_source_grpc_proto_source_proto_init() }
func file_pkg_source_grpc_proto_source_proto_init() {
	if File_pkg_source_grpc_proto_source_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_source_grpc_proto_source_proto_rawDesc), len(file_pkg_source_grpc_proto_source_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_source_grpc_proto_source_proto_goTypes,
		DependencyIndexes: file_pkg_source_grpc_proto_source_proto_depIdxs,
		MessageInfos:      file_pkg_source_grpc_proto_source_proto_msgTypes,
	}.Build()
	File_pkg_source_grpc_proto_source_proto = out.File
	file_pkg_source_grpc_proto_source_proto_goTypes = nil
	file_pkg_source_grpc_proto_source_proto_depIdxs = nil
}
