// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.2
// source: pkg/source/grpc/proto/source.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SourceService_Publish_FullMethodName       = "/hermod.source.grpc.v1.SourceService/Publish"
	SourceService_PublishStream_FullMethodName = "/hermod.source.grpc.v1.SourceService/PublishStream"
)

// SourceServiceClient is the client API for SourceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SourceService is how a producer pushes records into a Hermod gRPC source.
//
// This file is the whole contract: Hermod serves this one service, and there is
// nowhere to upload a .proto of your own. Generate a client from this file and
// send your record as JSON in PublishRequest.payload.
type SourceServiceClient interface {
	// Publish hands one record to the gRPC source registered for
	// PublishRequest.path. It returns as soon as the record is queued for the
	// workflow, unless the source is set to respond synchronously: then it
	// returns when the workflow has finished with the record, or when the
	// source's response timeout runs out.
	//
	// A source configured with an API key requires it as "x-api-key" metadata.
	//
	// PublishStream shares this request and response; see the note there.
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error)
	// PublishStream is Publish over one long-lived stream. Every record sent is
	// answered with one PublishResponse carrying that record's id, so a producer
	// can send many records without opening a call for each.
	//
	// Responses are sent as each record is answered. For a source that responds
	// synchronously that is when its workflow has finished with the record, so
	// responses can arrive in a different order from the requests: match them by
	// id. A record that could not be queued is answered "rejected" and the
	// stream stays open. A record the source's API key does not cover ends the
	// stream with an error. When the producer closes its side, the stream ends
	// once every record already sent has been answered.
	//
	// The request and response are Publish's on purpose: a record is the same
	// record whichever way it is sent.
	// buf:lint:ignore RPC_REQUEST_STANDARD_NAME
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	PublishStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PublishRequest, PublishResponse], error)
}

type sourceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSourceServiceClient(cc grpc.ClientConnInterface) SourceServiceClient {
	return &sourceServiceClient{cc}
}

func (c *sourceServiceClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, SourceService_Publish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceServiceClient) PublishStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PublishRequest, PublishResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SourceService_ServiceDesc.Streams[0], SourceService_PublishStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PublishRequest, PublishResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SourceService_PublishStreamClient = grpc.BidiStreamingClient[PublishRequest, PublishResponse]

// SourceServiceServer is the server API for SourceService service.
// All implementations must embed UnimplementedSourceServiceServer
// for forward compatibility.
//
// SourceService is how a producer pushes records into a Hermod gRPC source.
//
// This file is the whole contract: Hermod serves this one service, and there is
// nowhere to upload a .proto of your own. Generate a client from this file and
// send your record as JSON in PublishRequest.payload.
type SourceServiceServer interface {
	// Publish hands one record to the gRPC source registered for
	// PublishRequest.path. It returns as soon as the record is queued for the
	// workflow, unless the source is set to respond synchronously: then it
	// returns when the workflow has finished with the record, or when the
	// source's response timeout runs out.
	//
	// A source configured with an API key requires it as "x-api-key" metadata.
	//
	// PublishStream shares this request and response; see the note there.
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	Publish(context.Context, *PublishRequest) (*PublishResponse, error)
	// PublishStream is Publish over one long-lived stream. Every record sent is
	// answered with one PublishResponse carrying that record's id, so a producer
	// can send many records without opening a call for each.
	//
	// Responses are sent as each record is answered. For a source that responds
	// synchronously that is when its workflow has finished with the record, so
	// responses can arrive in a different order from the requests: match them by
	// id. A record that could not be queued is answered "rejected" and the
	// stream stays open. A record the source's API key does not cover ends the
	// stream with an error. When the producer closes its side, the stream ends
	// once every record already sent has been answered.
	//
	// The request and response are Publish's on purpose: a record is the same
	// record whichever way it is sent.
	// buf:lint:ignore RPC_REQUEST_STANDARD_NAME
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	PublishStream(grpc.BidiStreamingServer[PublishRequest, PublishResponse]) error
	mustEmbedUnimplementedSourceServiceServer()
}

// UnimplementedSourceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSourceServiceServer struct{}

func (UnimplementedSourceServiceServer) Publish(context.Context, *PublishRequest) (*PublishResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedSourceServiceServer) PublishStream(grpc.BidiStreamingServer[PublishRequest, PublishResponse]) error {
	return status.Error(codes.Unimplemented, "method PublishStream not implemented")
}
func (UnimplementedSourceServiceServer) mustEmbedUnimplementedSourceServiceServer() {}
func (UnimplementedSourceServiceServer) testEmbeddedByValue()                       {}

// UnsafeSourceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SourceServiceServer will
// result in compilation errors.
type UnsafeSourceServiceServer interface {
	mustEmbedUnimplementedSourceServiceServer()
}

func RegisterSourceServiceServer(s grpc.ServiceRegistrar, srv SourceServiceServer) {
	// If the following call panics, it indicates UnimplementedSourceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SourceService_ServiceDesc, srv)
}

func _SourceService_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceServiceServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourceService_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceServiceServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SourceService_PublishStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SourceServiceServer).PublishStream(&grpc.GenericServerStream[PublishRequest, PublishResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SourceService_PublishStreamServer = grpc.BidiStreamingServer[PublishRequest, PublishResponse]

// SourceService_ServiceDesc is the grpc.ServiceDesc for SourceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SourceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hermod.source.grpc.v1.SourceService",
	HandlerType: (*SourceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publish",
			Handler:    _SourceService_Publish_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PublishStream",
			Handler:       _SourceService_PublishStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/source/grpc/proto/source.proto",
}
