// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: inference.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PredictRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The vhost the model belongs to.
	Vhost string `protobuf:"bytes,1,opt,name=vhost,proto3" json:"vhost,omitempty"`
	// The model's name in that vhost.
	Model string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	// One object per row, with the fields the model takes.
	Instances     []*structpb.Struct `protobuf:"bytes,3,rep,name=instances,proto3" json:"instances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictRequest) Reset() {
	*x = PredictRequest{}
	mi := &file_inference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictRequest) ProtoMessage() {}

func (x *PredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictRequest.ProtoReflect.Descriptor instead.
func (*PredictRequest) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{0}
}

func (x *PredictRequest) GetVhost() string {
	if x != nil {
		return x.Vhost
	}
	return ""
}

func (x *PredictRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *PredictRequest) GetInstances() []*structpb.Struct {
	if x != nil {
		return x.Instances
	}
	return nil
}

type PredictResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The model that answered.
	Model string `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	// One object per row of the request, in the same order. A model with a
	// single output answers {"prediction": value}.
	Predictions   []*structpb.Struct `protobuf:"bytes,2,rep,name=predictions,proto3" json:"predictions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictResponse) Reset() {
	*x = PredictResponse{}
	mi := &file_inference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictResponse) ProtoMessage() {}

func (x *PredictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictResponse.ProtoReflect.Descriptor instead.
func (*PredictResponse) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{1}
}

func (x *PredictResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *PredictResponse) GetPredictions() []*structpb.Struct {
	if x != nil {
		return x.Predictions
	}
	return nil
}

var File_inference_proto protoreflect.FileDescriptor

const file_inference_proto_rawDesc = "" +
	"\n" +
	"\x0finference.proto\x12\fhermod.ml.v1\x1a\x1cgoogle/protobuf/struct.proto\"s\n" +
	"\x0ePredictRequest\x12\x14\n" +
	"\x05vhost\x18\x01 \x01(\tR\x05vhost\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x125\n" +
	"\tinstances\x18\x03 \x03(\v2\x17.google.protobuf.StructR\tinstances\"b\n" +
	"\x0fPredictResponse\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x129\n" +
	"\vpredictions\x18\x02 \x03(\v2\x17.google.protobuf.StructR\vpredictions2Z\n" +
	"\x10InferenceService\x12F\n" +
	"\aPredict\x12\x1c.hermod.ml.v1.PredictRequest\x1a\x1d.hermod.ml.v1.PredictResponseB)Z'github.com/gsoultan/hermod/pkg/ml/protob\x06proto3"

var (
	file_inference_proto_rawDescOnce sync.Once
	file_inference_proto_rawDescData []byte
)

func file_inference_proto_rawDescGZIP() []byte {
	file_inference_proto_rawDescOnce.Do(func() {
		file_inference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inference_proto_rawDesc), len(file_inference_proto_rawDesc)))
	})
	return file_inference_proto_rawDescData
}

var file_inference_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_inference_proto_goTypes = []any{
	(*PredictRequest)(nil),  // 0: hermod.ml.v1.PredictRequest
	(*PredictResponse)(nil), // 1: hermod.ml.v1.PredictResponse
	(*structpb.Struct)(nil), // 2: google.protobuf.Struct
}
var file_inference_proto_depIdxs = []int32{
	2, // 0: hermod.ml.v1.PredictRequest.instances:type_name -> google.protobuf.Struct
	2, // 1: hermod.ml.v1.PredictResponse.predictions:type_name -> google.protobuf.Struct
	0, // 2: hermod.ml.v1.InferenceService.Predict:input_type -> hermod.ml.v1.PredictRequest
	1, // 3: hermod.ml.v1.InferenceService.Predict:output_type -> hermod.ml.v1.PredictResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_inference_proto_init() }
func file_inference_proto_init() {
	if File_inference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inference_proto_rawDesc), len(file_inference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inference_proto_goTypes,
		DependencyIndexes: file_inference_proto_depIdxs,
		MessageInfos:      file_inference_proto_msgTypes,
	}.Build()
	File_inference_proto = out.File
	file_inference_proto_goTypes = nil
	file_inference_proto_depIdxs = nil
}
